pruebaMVC/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;

namespace pruebaMVC.Models
{
    [Table("person", Schema = "adm")] 
    public class Person
    {
        [Key]
        public int Id { get; set; }

        [Index("INDEX_ADM_PERSONA", 1, IsUnique = true)]	
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar el nombre de la persona.")]
        [StringLength(30, ErrorMessage = "El nombre de la persona no debe ser mayor de 30 caracteres.")]
        [Display(Name = "Nombre")]
        public string FirstName { get; set; }

        [Index("INDEX_ADM_PERSONA", 2, IsUnique = true)]

        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar el apellido de la persona.")]
        [StringLength(30, ErrorMessage = "El apellido de la persona no debe ser mayor de 30 caracteres.")]
        [Display(Name = "Apellido")]
        public string LastName { get; set; }

        public int TypeIdentificationId { get; set; }

        [Index("INDEX_ADM_PERSONA_IDENTIFICACION", IsUnique = true)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar la identificacion de la personae.")]
        [StringLength(20, ErrorMessage = "La identificacion de la persona no debe ser mayor de 20 caracteres.")]
        [Display(Name = "Identificacion")]
        public string Identification { get; set; }

        [Display(Name = "Activo")]
        public bool Active { get; set; }

        public virtual TypeIdentification TypeIdentifications { get; set; }
        //public virtual ICollection<TypeIdentificationId> TypeIdentificationIds { get; set; }

    }
}

pruebaMVC/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using pruebaMVC.Models;

namespace pruebaMVC.Controllers
{
    public class PersonsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index2()
        {

            ViewBag.TypeIdentificationId = new SelectList(db.TypeIdentifications.OrderBy(p => p.Name), "Id", "Name");
            return View();
        }

        public JsonResult GetPerson()
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<Person> output = db.Persons.ToList();
            return Json(output, JsonRequestBehavior.AllowGet);
        }

        // GET: Personas
        public ActionResult Index(string sort, string search, int? page)
        {
            ViewBag.NameSort = String.IsNullOrEmpty(sort) ? "name_desc" : string.Empty;
            ViewBag.ApellidoSort = sort == "apellido" ? "apellido_desc" : "apellido";
            ViewBag.TipoIdentificacionSort = sort == "tipoidentificacion" ? "tipoidentificacion_desc" : "tipoidentificacion";
            ViewBag.IdentificacionSort = sort == "identificacion" ? "identificacion_desc" : "identificacion";

            ViewBag.CurrentSort = sort;
            ViewBag.CurrentSearch = search;

            IQueryable<Person> personas = db.Persons;

            if (!String.IsNullOrEmpty(search))
                personas = personas.Where(p => p.FirstName.Contains(search) || p.LastName.Contains(search) || p.Identification.Contains(search) 
                    || p.TypeIdentifications.Name.Contains(search));

            switch (sort)
            {
                case "name":
                    personas = personas.OrderBy(p => p.FirstName)
                                        .ThenBy(p => p.LastName);
                    break;

                case "name_desc":
                    personas = personas.OrderByDescending(p => p.FirstName)
                                        .ThenBy(p => p.LastName);
                    break;

                case "apellido":
                    personas = personas.OrderBy(p => p.LastName).ThenBy(p => p.FirstName);

                    break;
                case "apellido_desc":
                    personas = personas.OrderByDescending(p => p.LastName).ThenBy(p => p.FirstName);
                    break;

                case "tipoidentificacion":
                    personas = personas.OrderBy(p => p.TypeIdentifications.Name)
                                        .ThenBy(p => p.FirstName)
                                        .ThenBy(p => p.LastName);
                    break;

                case "tipoidentificacion_desc":
                    personas = personas.OrderByDescending(p => p.TypeIdentifications.Name)
                                        .ThenBy(p => p.FirstName)
                                        .ThenBy(p => p.LastName);;
                    break;

                case "identificacion":
                    personas = personas.OrderBy(p => p.Identification);

                    break;
                case "identificacion_desc":
                    personas = personas.OrderByDescending(p => p.Identification);
                    break;

                default:
                    personas = personas.OrderBy(p => p.FirstName)
                                        .ThenBy(p => p.LastName);
                    break;
            }

            int pageSize = 5;
            int pageNumber = page ?? 1;         //si viene nulo asignar pagina 1

            //return View(await personas.ToListAsync());
            return View(personas.ToPagedList(pageNumber, pageSize));
        }

        // GET: Personas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person persona = await db.Persons.FindAsync(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // GET: Personas/Create
        public ActionResult Create()
        {
            ViewBag.TypeIdentificationId = new SelectList(db.TypeIdentifications.OrderBy(p => p.Name), "Id", "Name");

            return View();
        }

        // POST: Personas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "FirstName,LastName,TypeIdentificationId,Identification,Active")] Person persona)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Persons.Add(persona);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    var e = ex.GetBaseException() as SqlException;
                    if (e != null)
                        switch (e.Number)
                        {
                            case 2601:
                                TempData["MessageToClient"] = String.Format("DATOS DUPLICADOS DEL REGISTRO A GUARDAR.");
                                break;
                            default:
                                throw;
                        }
                }
            }

            return View(persona);
        }

        // GET: Personas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person persona = await db.Persons.FindAsync(id);

            ViewBag.TypeIdentificationId = new SelectList(db.TypeIdentifications.OrderBy(p => p.Name), "Id", "Name", persona.TypeIdentificationId);

            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: Personas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,FirstName,LastName,TypeIdentificationId,Identification,Active")] Person persona)
        {
            if (ModelState.IsValid)
            {
                db.Entry(persona).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.TypeIdentificationId = new SelectList(db.TypeIdentifications.OrderBy(p => p.Name), "Id", "Name", persona.TypeIdentificationId);
            return View(persona);
        }

        // GET: Personas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person persona = await db.Persons.FindAsync(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Person persona = await db.Persons.FindAsync(id);
            db.Persons.Remove(persona);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pruebaMVC/Views/Persons/Create.cshtml
@model pruebaMVC.Models.Person

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />
        <h4><p class="text-danger">@TempData["MessageToClient"]</p></h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.TypeIdentifications.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeIdentificationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeIdentifications.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TypeIdentificationId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeIdentificationId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeIdentificationId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Identification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Identification, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Identification, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

pruebaMVC/Views/Persons/Delete.cshtml
@model pruebaMVC.Models.Person

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.TypeIdentifications.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeIdentifications.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Identification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identification)
        </dd>
        
        <dt>
        @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

pruebaMVC/Views/Persons/Details.cshtml
@model pruebaMVC.Models.Person

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.TypeIdentifications.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeIdentifications.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Identification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identification)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

pruebaMVC/Views/Persons/Edit.cshtml
@model pruebaMVC.Models.Person

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        @*<div class="form-group">
            @Html.LabelFor(model => model.TypeIdentificationId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeIdentificationId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeIdentificationId, "", new { @class = "text-danger" })
            </div>
        </div>*@
        
        <div class="form-group">
            @Html.LabelFor(model => model.TypeIdentifications.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeIdentificationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeIdentifications.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Identification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Identification, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Identification, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

pruebaMVC/Views/Persons/Index.cshtml
@*@model IEnumerable<pruebaMVC.Models.Persona>*@

@using PagedList.Mvc
@model PagedList.IPagedList<pruebaMVC.Models.Person>

<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "Registro Persona";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Persons", FormMethod.Get, new {@class = "form-inline"}))
{
    @Html.Label("search", "Nombre, apellido o cedula: ", new {@class="control-label"})
    @Html.TextBox("search",ViewBag.CurrentSearch as string, new { @class = "form-control" })
    <input type="submit" value="Search" class="btn btn-default"/>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Name)*@
            @Html.ActionLink("Nombre", "Index", new { sort = ViewBag.NameSort, search = ViewBag.CurrentSearch})
        </th>
        <th>
            @* @Html.DisplayNameFor(model => model.Apellido)*@
            @Html.ActionLink("Apellido", "Index", new { sort = ViewBag.ApellidoSort, search = ViewBag.CurrentSearch })
        </th>
        
        <th>
            @*@Html.DisplayNameFor(model => model.Identificacion)*@
            @Html.ActionLink("Tipo Identificacion", "Index", new { sort = ViewBag.TipoIdentificacionSort, search = ViewBag.CurrentSearch })
        </th>

        <th>
            @*@Html.DisplayNameFor(model => model.Identificacion)*@
            @Html.ActionLink("Identificacion", "Index", new { sort = ViewBag.IdentificacionSort, search = ViewBag.CurrentSearch })
        </th>
        
        <th>
            @*@Html.DisplayNameFor(model => model.Identificacion)*@
            @Html.ActionLink("Activo", "Index", new { sort = ViewBag.IdentificacionSort, search = ViewBag.CurrentSearch })
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeIdentifications.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Identification)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }

</table>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new {page, sort = ViewBag.CurrentSort, search = ViewBag.CurrentSearch}))